--- #YAML:1.0
name:               Mojolicious-Plugin-PlackMiddleware
version:            0.19
abstract:           Plack::Middleware inside Mojolicious
author:
    - Sugama Keita <sugama@jamadam.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Mojolicious:          1.65
    Plack:                0.9944
    Test::Class:          0.36
    Test::More:           0.47
    Test::UseAllModules:  0.10
requires:  {}
resources:
    repository:  
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
